# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1a1bdbff8c691e85c12974a1cc8c95868dda66d4f3a5dce6de27145a78c60746c0c834b4c48d96f406c18fd9b97e3878a3750c3951c5fd4f993c2d9ac897862

test:
  secret_key_base: 43cccd582269086b18f8e19b35ad89fe430c11271b8e71286ae7060a656ca495909d22da4d5288f05fea0771ede6525b56a689e6295a2c82b81fbf8c900aa947

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
